### ISSUE TITLE
when i app reinstall clearing all my chat messages

### ISSUE THREAD

**Issue by RMVIVEK55** [freshworks/freshchat-android#116]
1.main activity:
override fun onCreate(savedInstanceState: Bundle?) {
val config = FreshchatConfig(APPID, APPKEY)
        config.domain = Domain
        config.setResponseExpectationEnabled(true)
        config.setTeamMemberInfoVisible(true)
        config.isCameraCaptureEnabled = true
        config.isGallerySelectionEnabled = true
        config.isResponseExpectationEnabled = true
        Freshchat.getInstance(applicationContext).init(config)
}
------------------------------------------------------------------------------------
class 2:
class FrashChatActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_chat)
        var SharedPreferenceUtils = MyPreferences(this)

        var pickMeLocals= PickMeLocals.instance
        val customerinfoobject=pickMeLocals.getCustomerSharedInfo()

        Freshchat.getInstance(getApplicationContext()).identifyUser(customerinfoobject.Customer_Email_Address!!, null);
        val restoreId = Freshchat.getInstance(applicationContext).user.restoreId
        Log.e("restoreId",restoreId)
        Freshchat.getInstance(getApplicationContext()).identifyUser(customerinfoobject.Customer_Email_Address!!, restoreId);

                            val eventName = "Visited Order Details page"

                            var  userID = SharedPreferenceUtils.getString(MyPreferences.UserID)
                            val freshchatUser1 = Freshchat.getInstance(applicationContext).user
                            val properties: HashMap<String, Any> = HashMap()
                            properties.put("From_Id", userID!!)
                            properties.put("To_Id", "???")

                            properties.put("firstName",customerinfoobject.Customer_First_Name!!)
                            properties.put("lastName",customerinfoobject.Customer_Last_Name!!)
                            properties.put("email",customerinfoobject.Customer_Email_Address!!)
                            properties.put("Phone","+91"+ customerinfoobject.Customer_Mobile_Number.toString())
                            properties.put("Store_Name", "Gaja")
                            properties.put("Text", "hellow")
                         //   Freshchat.trackEvent(this, eventName, properties);

        img_send.setOnClickListener {

            Freshchat.showConversations(getApplicationContext());

        }

    }
}
-------------------------------------------------------------------

**Comment by rameshfreshworks** [comment]
Hi @RMVIVEK55 
 Freshchat generates a restoreID for a new user(passing only external id and restore id as null) whenever the user initiates a chat. This happens very first the user is being identified. 

 Listen for FRESHCHAT_USER_RESTORE_ID_GENERATED event, save the RestoreId received against the external ID in your server.

 Store the restoreID provided by Freshchat against given externalID in your server or any persistence storage for restoring chat of the user.

 When you identify the same user again pass the externalId and restoreId(if exists, null otherwise) combination. This will restore the user's old chat as expected .

We would need the both externalId and restoreId values coming from your app for user restore.

Freshchat.getInstance(context).identifyUser( exteralId, freshchatRestoreID); 

Refer section 3.5 in the [documentation](https://support.freshchat.com/en/support/solutions/articles/50000000207-freshchat-android-sdk-integration-steps) on how to implement this.

**Comment by RMVIVEK55** [comment]
am use this code app clear all message 
Freshchat.getInstance(getApplicationContext()).identifyUser(customerinfoobject.Customer_Email_Address!!, null);

**Comment by rameshfreshworks** [comment]
When restoreId is null, Freshchat considers this as a new user. Hence the messages are cleared.  Freshchat expects both externalId( customer email in this case) and restoreId to be passed to successfully restore an existing user.

**Comment by RMVIVEK55** [comment]
Thanks, @rameshfreshworks Working fine for explanation

**Comment by RMVIVEK55** [comment]
Woking fine
