### ISSUE TITLE
showConversations() open two modals - React-native

### ISSUE THREAD

**Issue by rehancg** [freshworks/freshchat-android#133]
## Describe the bug
on some android devices, while navigating to inbox page (showConversations()), there's another screen (Converstaions) that shows up and closes. I guess this is with android 10 devices.

## Steps to reproduce
```    
Init react-native-fresh-chat-sdk
invoke function -  showConversations()
It navigates to Coversations->Inbox
```

## Expected behavior
Directly navigate to inbox page

## Platform
- [ ] Android
- [ ] React Native

## Freshchat SDK version
- SDK version : 3.3.2
- React Native version (if applicable) : 0.63.4

## Device information
Not sure, but i guess on all Android 10 devices
```
 * Device name - Redmi Note 7
 * OS version - 10
```

**Comment by rameshfreshworks** [comment]
Hi @rehancg , 
I believe you are talking about an intermediate screen that appears when you call ShowConversations() API. If yes, This happens when there is only one topic. 

To avoid this behavior, please set a tag to that topic and pass ConversationOptions with set tag value as a param to ShowConversations() API.

Refer section 4.1.1 in [documentation](https://support.freshchat.com/en/support/solutions/articles/50000000207-freshchat-android-sdk-integration-steps) for more details.

**Comment by MuthuFD** [comment]
Hi @rehancg ,
I hope our above reply was helpful in resolving your query. 
If you still face issues, please feel free to reach out to us at support@freshchat.com
