### ISSUE TITLE
ID Mismatch when working with MultiUser on a save device.

### ISSUE THREAD

**Issue by nishanth0299** [freshworks/freshchat-android#137]
## Describe the bug
ID Mismatch when working with MultiUser on a save device.
We have build a multiuser feature on our app which allow multiple persons to login into the same app.
On logging into child 1 and sending a message to Freshchat. The broadcast receiver returns the main user's identifier id instead of user1's id.
## Steps to reproduce
```
* Step 1 - Create and login to main profile
* Step 2 - Create two child accounts
* Step 3 - Now we have 3 active account on a single device
* Step 4 - Click Switch profile and login to Child 1
* Step 5 - On switching we are calling Freshchat.getInstance(getApplicationContext()).identifyUser(identifier, null);
* Step 5 - Send message to Freshchat
* Step 6 - The broadcast reciever of restore ID spits our main profile ID as the externalID
```
## Expected behavior
The broadcast receiver should always give the correct identifier and restore Id.
## Platform
- Android
## Freshchat SDK version
- SDK version : 4.3.4
## Device information
- [ ] is reproducible on all devices?
Yes
```
Provide device details here like
 * Device name OnePlus 7T
 * OS version 11
```

**Comment by rameshfreshworks** [comment]
Hi @nishanth0299 ,
Freshchat requires an unique id as external id for each user that your app supports. This way the same user's chat history can be restored across sessions and devices. 

So, we suggest you to pass unique id for each user say child1 in this case. The restore id is generated when an Freshchat user is created for child1. This freshchat user creation happens when user sends his first message on chat. 
Listen for and store restore id provided by freshchat in your server. Use this same restore id when you want to restore chat that belongs child1.

Use the same identifyUser API to restore an user.
 ```Freshchat.getInstance(getApplicationContext()).identifyUser(identifier, Freshchat restore Id);```
  
Freshchat expects correct combo of external id and restore id to successfully restore an user.

**Comment by rameshfreshworks** [comment]
Hope our above solution solves your issue.
If you need more help, please contact us through support@freshchat.com
